environmentvariabledefinition:
  '@schemaname': sci_ghops4_1779200853581
  description:
    '@default': Auto-created by automated test suite – safe to delete
    label:
      '@description': Auto-created by automated test suite – safe to delete
      '@languagecode': 1033
  displayname:
    '@default': Test Var sci_ghops4_1779200853581
    label:
      '@description': Test Var sci_ghops4_1779200853581
      '@languagecode': 1033
  introducedversion: 1.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
