environmentvariabledefinition:
  '@schemaname': cr79e_env2
  displayname:
    '@default': env2
    label:
      '@description': env2
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
