environmentvariabledefinition:
  '@schemaname': cr79e_env1
  displayname:
    '@default': env1
    label:
      '@description': env1
      '@languagecode': 1033
  introducedversion: 1.0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
